### PR TITLE
Fix build and update to latest versions

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Review by mumbozver — COMMENTED** [review]
you probably need to add
`                "apply_extra"`
 I haven't found output of this script in build logs.
 Hope no need of something bigger

**Comment by akurtakov** [comment]
> you probably need to add explicit call of ` "apply_extra"` I haven't found output of this script in build logs. Hope no need of something bigger

Where do I have to put this apply_extra call? I would appreciate further guidance.

**Comment by mumbozver** [comment]
> Where do I have to put this apply_extra call? I would appreciate further guidance.

I'd try to insert it as last build command here:
https://github.com/flathub/com.viber.Viber/blob/master/com.viber.Viber.json#L39

It's first time I'm touching flatpak, it's just wild guess.

**Comment by TingPing** [comment]
`apply_extra` is automatically called at install time.

**Comment by TingPing** [comment]
Here was my attempt: https://github.com/flathub/com.viber.Viber/pull/86

**Pull request closed without merging**
